import { randomUUID } from "crypto";
import type { Category, Reward, TouristSpot } from "./types.js";

const now = () => new Date().toISOString();

export const categorySeed = (): Category[] => [
  { id: "cat-agri", slug: "agri-tourism", name: "Agri-tourism", description: "Farms, fruit parks, and harvest experiences", icon: "Sprout" },
  { id: "cat-nature", slug: "nature", name: "Nature", description: "Highlands, waterfalls, and mountain views", icon: "Mountain" },
  { id: "cat-faith", slug: "faith-heritage", name: "Faith & heritage", description: "Pilgrimage sites and local culture", icon: "Church" },
  { id: "cat-leisure", slug: "leisure", name: "Leisure & springs", description: "Resorts, picnic grounds, and family stops", icon: "Waves" },
  { id: "cat-food", slug: "food-market", name: "Food & market", description: "Fruit stalls, local produce, and town flavors", icon: "ShoppingBasket" },
];

export const rewardSeed = (): Reward[] => [
  { id: "rw-1", name: "Tupi Explorer sticker pack", description: "Digital badge pack celebrating Tupi agri-tourism.", pointsCost: 80, stock: 200, active: true },
  { id: "rw-2", name: "Fruit Park tasting voucher note", description: "A redeemable visit note you can show at participating stalls. Not cash.", pointsCost: 180, stock: 40, active: true },
  { id: "rw-3", name: "Local guide shout-out", description: "Feature your Tupi trip story in the community feed.", pointsCost: 120, stock: 80, active: true },
];

export const badgeSeed = [
  { id: "bd-1", slug: "first-adventure", name: "First Adventure", description: "Checked in at your first Tupi destination." },
  { id: "bd-2", slug: "tupi-explorer", name: "Tupi Explorer", description: "Visited 3 destinations in Tupi." },
  { id: "bd-3", slug: "nature-seeker", name: "Nature Seeker", description: "Favorited nature and highland spots." },
  { id: "bd-4", slug: "local-discoverer", name: "Local Discoverer", description: "Wrote your first review." },
  { id: "bd-5", slug: "tupi-champion", name: "Tupi Champion", description: "Earned 300 explorer points." },
];

export const spotSeed = (): TouristSpot[] => {
  const ts = now();
  return [
    {
      id: "sp-sg-farm",
      slug: "sg-farm-kablon",
      name: "SG Farm (Strawberry–Guyabano Farm)",
      categoryId: "cat-agri",
      shortDescription: "Tupi’s highland farm with Matutum views, berries, and cool air in Sitio Glandang.",
      description:
        "SG Farm in Sitio Glandang, Barangay Kablon is one of Tupi’s best-known agri-tourism stops. Provincial tourism reports have ranked it among South Cotabato’s most visited attractions. Visitors come for strawberry and guyabano plantings, mountain air, and a backdrop of Mt. Matutum. Confirm current picking seasons, fees, and opening hours with the farm before you go — those details change with harvest and weather.",
      lat: 6.3785,
      lng: 124.9952,
      address: "Sitio Glandang, Barangay Kablon, Tupi, South Cotabato",
      barangay: "Kablon",
      amenities: ["Scenic viewpoint", "Farm walk", "Food stalls (seasonal)", "Parking (limited)"],
      operatingHours: { days: "Typically daily", hours: "Confirm with farm", reliability: "estimated" },
      featured: true,
      status: "approved",
      dataSource: "curated",
      estimatedEntranceFee: 50,
      popularityScore: 98,
      viewCount: 1280,
      visitCount: 410,
      images: [
        { url: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=1600&q=80", alt: "Ripe strawberries in a farm row" },
        { url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&q=80", alt: "Green highland landscape" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-fruit-park",
      slug: "tupi-fruit-park",
      name: "Tupi Fruit Park",
      categoryId: "cat-food",
      shortDescription: "Organized fruit trading park in Kablon along the national highway, with Matutum as backdrop.",
      description:
        "Tupi Fruit Park in Barangay Kablon gathers fruit vendors into a purpose-built roadside park. Tupi is widely known as a fruit and flower basket of South Cotabato; travelers stop here for pineapples, papayas, bananas, and other local produce. It is a practical first stop if you are entering town from the national highway. Prices and stall hours vary by vendor.",
      lat: 6.3528,
      lng: 124.9741,
      address: "National Highway, Barangay Kablon, Tupi, South Cotabato",
      barangay: "Kablon",
      amenities: ["Fruit stalls", "Highway access", "Photo spot", "Parking"],
      operatingHours: { days: "Daily", hours: "Daylight hours, stall-dependent", reliability: "estimated" },
      featured: true,
      status: "approved",
      dataSource: "curated",
      popularityScore: 92,
      viewCount: 980,
      visitCount: 360,
      images: [
        { url: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=1600&q=80", alt: "Fresh pineapples" },
        { url: "https://images.unsplash.com/photo-1577234283474-ec2cdb884c4d?w=1600&q=80", alt: "Tropical fruit display" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-mariano",
      slug: "marianos-blooming-park",
      name: "Mariano’s Blooming Agri-Tourism Park",
      categoryId: "cat-agri",
      shortDescription: "Flower and agri-tourism park with sunflower fields and wide garden walks.",
      description:
        "Mariano’s Blooming Agri-Tourism Park is a large garden and farm experience in Tupi, often visited for sunflower and ornamental plantings. Travelers typically budget at least two hours if they want more than a quick photo stop. Bloom quality depends on season and farm scheduling — ask locally or check recent visitor notes before planning around a specific flower.",
      lat: 6.3291,
      lng: 124.9518,
      address: "Tupi, South Cotabato",
      barangay: "Poblacion area / nearby barangays",
      amenities: ["Flower fields", "Walking paths", "Photo gardens", "Family-friendly"],
      operatingHours: { days: "Confirm before visit", hours: "Usually daytime", reliability: "estimated" },
      featured: true,
      status: "approved",
      dataSource: "curated",
      estimatedEntranceFee: 100,
      popularityScore: 88,
      viewCount: 860,
      visitCount: 290,
      images: [
        { url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=1600&q=80", alt: "Sunflower field" },
        { url: "https://images.unsplash.com/photo-1462275646964-a0e3386b89fa?w=1600&q=80", alt: "Garden path with blossoms" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-magsangyaw",
      slug: "magsangyaw-land-of-praise",
      name: "Magsangyaw Land of Praise",
      categoryId: "cat-faith",
      shortDescription: "Hilltop faith destination with wide views of Tupi’s mountains and fields.",
      description:
        "Magsangyaw Land of Praise is a well-known pilgrimage and viewpoint destination in Tupi. Visitors come for prayer, quiet, and a panoramic look over surrounding green highlands. Wear comfortable shoes, bring water, and expect cooler air than in the lowland barangays. Activity schedules for gatherings should be confirmed with organizers.",
      lat: 6.3412,
      lng: 124.9386,
      address: "Mountain peak area, Tupi, South Cotabato",
      barangay: "Upland Tupi",
      amenities: ["Viewpoint", "Prayer area", "Photo decks"],
      operatingHours: { days: "Typically open daytime", hours: "Confirm locally", reliability: "estimated" },
      featured: true,
      status: "approved",
      dataSource: "curated",
      popularityScore: 84,
      viewCount: 720,
      visitCount: 210,
      images: [
        { url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1600&q=80", alt: "Mountain view above green fields" },
        { url: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1600&q=80", alt: "Open highland landscape" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-matutum",
      slug: "mount-matutum-tupi-views",
      name: "Mt. Matutum views (Tupi side)",
      categoryId: "cat-nature",
      shortDescription: "Iconic volcano skyline seen from Tupi’s Kablon and Glandang highlands.",
      description:
        "Mt. Matutum dominates the skyline of Tupi, especially from Barangay Kablon and Sitio Glandang. This listing is for roadside and farm viewpoints on the Tupi side — not a summit climb itinerary. Climbing Matutum requires permits, guides, and current trail advice from the proper authorities. For most visitors, the Tupi experience is a scenic stop combined with farms and the fruit park.",
      lat: 6.3614,
      lng: 125.0048,
      address: "Viewpoints toward Mt. Matutum, Tupi, South Cotabato",
      barangay: "Kablon",
      amenities: ["Scenic lookout", "Photography", "Cool climate"],
      operatingHours: { days: "Daylight", hours: "Best in clear mornings", reliability: "estimated" },
      featured: true,
      status: "approved",
      dataSource: "curated",
      popularityScore: 90,
      viewCount: 1100,
      visitCount: 180,
      images: [
        { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&q=80", alt: "Mountain peak above clouds" },
        { url: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1600&q=80", alt: "Highland road with mountain backdrop" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-taal-falls",
      slug: "taal-falls",
      name: "Taal Falls",
      categoryId: "cat-nature",
      shortDescription: "Bridal-veil cascade with cold pools; access can involve a farm and river approach.",
      description:
        "Taal Falls is a curtain-like cascade visited from the Tupi–Tampakan upland corridor. Travelers describe cold water, shallow pools, and a scenic approach that may include habal-habal rides, farm tracks, and river crossings. Conditions change after rain. There is no single official published fee in this catalog — treat cost and access as estimated and confirm locally. Leave no trash; visitors have reported litter problems.",
      lat: 6.4011,
      lng: 125.0215,
      address: "Upland corridor near Tupi / Tampakan, South Cotabato",
      barangay: "Upland (confirm access barangay locally)",
      amenities: ["Swimming (natural pool)", "Trek", "Nature photography"],
      operatingHours: { days: "Weather dependent", hours: "Daylight only", reliability: "estimated" },
      featured: false,
      status: "approved",
      dataSource: "curated",
      popularityScore: 76,
      viewCount: 540,
      visitCount: 95,
      images: [
        { url: "https://images.unsplash.com/photo-1432405972473-1d8d7647da18?w=1600&q=80", alt: "Waterfall in a forested gorge" },
        { url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1600&q=80", alt: "Forest stream" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-shellrock",
      slug: "shellrock-spring-resort",
      name: "Shellrock Spring Resort",
      categoryId: "cat-leisure",
      shortDescription: "Family spring resort setting with cold water, huts, and picnic space.",
      description:
        "Shellrock Spring Resort is a local leisure stop associated with Tupi visits — cold spring water, cottage-style rest areas, and family gatherings. Amenities and day-use rates should be confirmed directly with the resort. This catalog does not invent a price list; ask on-site or by phone before you travel with a large group.",
      lat: 6.3188,
      lng: 124.9612,
      address: "Tupi, South Cotabato",
      barangay: "Confirm with resort",
      amenities: ["Spring pools", "Cottages", "Picnic area", "Parking"],
      operatingHours: { days: "Confirm with resort", hours: "Usually daytime to evening", reliability: "estimated" },
      featured: false,
      status: "approved",
      dataSource: "curated",
      estimatedEntranceFee: 80,
      popularityScore: 70,
      viewCount: 410,
      visitCount: 140,
      images: [
        { url: "https://images.unsplash.com/photo-1540541338287-41700290dee9?w=1600&q=80", alt: "Resort pool and palms" },
        { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&q=80", alt: "Clear water" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-poblacion",
      slug: "tupi-poblacion",
      name: "Tupi Poblacion & public market",
      categoryId: "cat-food",
      shortDescription: "Town proper — jeepney connections, market produce, and a practical trip starting point.",
      description:
        "Tupi Poblacion is the civic and transport heart of the municipality. Use it as a starting location for itineraries: tricycles to farms, buses along the Koronadal–Polomolok corridor, and market food. It is not a gated tourist attraction; it is the real town. Pair it with the fruit park if you want a fuller local-produce day.",
      lat: 6.3347,
      lng: 124.9669,
      address: "Poblacion, Tupi, South Cotabato",
      barangay: "Poblacion",
      amenities: ["Public market", "Tricycle hub", "Eateries", "Services"],
      operatingHours: { days: "Daily", hours: "Market strongest in the morning", reliability: "estimated" },
      featured: false,
      status: "approved",
      dataSource: "curated",
      popularityScore: 65,
      viewCount: 300,
      visitCount: 220,
      images: [
        { url: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1600&q=80", alt: "Open air market produce" },
        { url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=1600&q=80", alt: "Fresh vegetables at market" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-pineapple",
      slug: "tupi-pineapple-country",
      name: "Tupi pineapple country (plantation views)",
      categoryId: "cat-agri",
      shortDescription: "Roadside plantation landscapes that explain why Tupi is called a fruit basket.",
      description:
        "Large pineapple and banana plantations shape Tupi’s countryside, especially along routes toward Polomolok and upland barangays. This listing highlights landscape viewing and photography from public roads — plantation interiors are private working farms. Do not enter fields without permission. Combine with Tupi Fruit Park if you want to buy fruit legally from vendors.",
      lat: 6.3224,
      lng: 124.9826,
      address: "Plantation corridor, Tupi, South Cotabato",
      barangay: "Multiple barangays",
      amenities: ["Scenic roadside views", "Photography from public roads"],
      operatingHours: { days: "Daylight", hours: "Anytime from public roads", reliability: "verified" },
      featured: false,
      status: "approved",
      dataSource: "curated",
      popularityScore: 72,
      viewCount: 390,
      visitCount: 70,
      images: [
        { url: "https://images.unsplash.com/photo-1589820296156-2454bb8a6ad1?w=1600&q=80", alt: "Pineapple growing in a field" },
        { url: "https://images.unsplash.com/photo-1490885578174-acda8905c2c6?w=1600&q=80", alt: "Tropical plantation landscape" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "sp-kablon-highlands",
      slug: "kablon-highlands",
      name: "Kablon highlands",
      categoryId: "cat-nature",
      shortDescription: "Cool upland barangay connecting the fruit park, SG Farm, and Matutum views.",
      description:
        "Barangay Kablon is Tupi’s highland gateway. Cooler weather, vegetable and fruit growing, and mountain scenery make it the natural cluster for a half-day trip: Fruit Park + SG Farm + Matutum viewpoints. Roads can be steep and misty. Travel early if you are using public transport back to Poblacion.",
      lat: 6.3602,
      lng: 124.9844,
      address: "Barangay Kablon, Tupi, South Cotabato",
      barangay: "Kablon",
      amenities: ["Cool climate", "Farm stands", "Mountain roads"],
      operatingHours: { days: "Daily", hours: "Daylight recommended", reliability: "estimated" },
      featured: false,
      status: "approved",
      dataSource: "curated",
      popularityScore: 80,
      viewCount: 450,
      visitCount: 125,
      images: [
        { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1600&q=80", alt: "Misty mountain road" },
        { url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1600&q=80", alt: "Lush highland forest" },
      ],
      createdAt: ts,
      updatedAt: ts,
    },
  ];
};

export const newId = () => randomUUID();
